### ISSUE TITLE
Sintesis JuanCarlosChavez Santiago

### ISSUE THREAD

**Issue by CarlosSD16** [SistemasTecTlaxiaco/sintesis-CarlosSD16#2]
[sistesis.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-CarlosSD16/files/7151287/sistesis.pdf)

**Comment by Edwin-1012** [comment]
Revisado calificación 20 % se enfoco en los puntos primordiales vistos en la clase y como se aplican al nuestro.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
